Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Spring-2025

frontend/src/main/frontend/src/components/QuoteForm.jsx

A very simple, bare bone version of what the user will use to upload a quote to the database. Literally just two text inputs and a button that prints the inputs to the console. My best React work yet. 
Originally was written on my Fork of this project and I have ripped it from that fork to this branch. Will be using this branch more often from now on.

A very simple QuoteForm.

---

frontend/src/main/frontend/index.html
frontend/src/main/frontend/src/App.css
frontend/src/main/frontend/src/App.jsx
frontend/src/main/frontend/src/components/Layout.jsx
frontend/src/main/frontend/src/components/TopNavigation.jsx
frontend/src/main/frontend/src/pages/LandingPage.jsx

- Created a top navigation bar and set up a layout for all pages/components
- Added references to jquery and bootstrap
- Set up global property isLoggedIn

top-nav and overall layout

---

frontend/src/main/frontend/package-lock.json
frontend/src/main/frontend/package.json
frontend/src/main/frontend/src/components/QuoteCard.jsx

Quotecard Components

---

_backend/services/quote-service/src/main/java/com/quotes/MongoUtil.java
_backend/services/quote-service/src/main/liberty/config/server.xml
_backend/services/user-service/src/main/liberty/config/server.xml

Tested a basic @GET API request from our quote-service and successfully got a response, so communication between frontend and backend services has been established.
I also fixed a minor issue with search querying that was resulting in an error code.

Fixed CORS policy config + minor bug fix

---

frontend/src/main/frontend/.env
frontend/src/main/frontend/src/components/QuoteUploadModal.jsx
frontend/src/main/frontend/src/lib/api.js
frontend/src/main/frontend/src/pages/LandingPage.jsx

Cors is still causing issues with changes, discarded server.xml changes

API connection, quote upload and bookmarked display

---

_backend/services/quote-service/src/main/java/com/quotes/MongoUtil.java
_backend/services/quote-service/src/main/java/com/quotes/QuoteCreateResource.java
_backend/services/quote-service/src/main/java/com/quotes/QuoteDeleteResource.java
_backend/services/quote-service/src/main/java/com/quotes/QuoteSearchResource.java
_backend/services/quote-service/src/main/java/com/quotes/QuotesUpdateResource.java
_backend/services/quote-service/src/main/java/com/quotes/SanitizerClass.java
_backend/services/quote-service/src/main/liberty/config/server.xml
_backend/services/user-service/src/main/liberty/config/server.xml
frontend/src/main/frontend/src/App.jsx
frontend/src/main/frontend/src/lib/api.js
frontend/src/main/frontend/src/pages/DebugPage.jsx

Added annotations for quote service, and update to CORs configuration

API Annotations + CORs 

---

_backend/services/user-service/src/main/java/com/accounts/AccountService.java
_backend/services/user-service/src/main/java/com/accounts/AccountsResource.java
_backend/services/user-service/src/main/java/com/auth/AuthResource.java
_backend/services/user-service/src/main/java/com/auth/JwtService.java
_backend/services/user-service/src/main/liberty/config/server.xml
frontend/src/main/frontend/src/components/Layout.jsx
frontend/src/main/frontend/src/components/TopNavigation.jsx
frontend/src/main/frontend/src/lib/api.js
frontend/src/main/frontend/src/pages/LandingPage.jsx
frontend/src/main/frontend/vite.config.js

ok so basically I had to ditch the assymetric key way of doing the JWTs because after playing with it for about 2 hours, I couldn't get it to work after basically following the tutorials to a tee, so instead of using RS256 (RSA, assymetric 256 bit encryption), it's currently using HS256 (HMAC, 256 bit encryption).
I changed the config files to make this work, and probably made some bad coding decisions considering it is *literally* 5 am, but it's done, and it's not smoke & mirrors, so I'll take it.

WORKING LOGIN

---

frontend/src/main/frontend/src/components/AlertMessage.jsx
frontend/src/main/frontend/src/components/QuoteForm.jsx
frontend/src/main/frontend/src/components/QuoteUploadModal.jsx
frontend/src/main/frontend/src/pages/LandingPage.jsx

Styling aligns better with usability

JV Styling changes + pill tags, alert messages

---

frontend/src/main/frontend/src/components/TopNavigation.jsx

Added and changed elements of the Navigation Bar to better mimic Usability's diagram. 
- Logo now appears on the left, Home on the right.  
- Users now see Upload Quote and Saved links after the Home link. 
Didn't get around to adding functionality to the Upload Quote link. Not sure how we're going to implement uploading quotes yet.

Changes to Navigation Bar

---

_backend/services/quote-service/src/main/java/com/quotes/MongoUtil.java
_backend/services/quote-service/src/main/java/com/quotes/QuoteDeleteResource.java
_backend/services/quote-service/src/main/java/com/quotes/QuoteObject.java
_backend/services/quote-service/src/main/java/com/quotes/QuotesUpdateResource.java

Added privacy field and functionality. Added quote creator field.

Added new quotes fields

---

_backend/services/quote-service/pom.xml
_backend/services/quote-service/src/test/java/quotes/QuoteApiIT.java
_backend/services/quote-service/src/test/java/quotes/QuoteApiTests.java
_backend/services/user-service/pom.xml

Added basic test cases for our quote API endpoints

Added QuoteAPI tests for Quote Services

---

frontend/src/main/frontend/src/components/TopNavigation.jsx
frontend/src/main/frontend/src/pages/LoginPage.jsx

new nav updates did not include linking to uploading quotes modal, fixed for QA

linking upload back

---

_backend/services/quote-service/pom.xml
_backend/services/quote-service/src/main/java/com/quotes/QuoteCreateResource.java
_backend/services/quote-service/src/main/java/com/quotes/QuoteDeleteResource.java
_backend/services/quote-service/src/main/java/com/quotes/QuotesRetrieveAccount.java
_backend/services/quote-service/src/main/java/com/quotes/QuotesUpdateResource.java
_backend/services/quote-service/src/main/liberty/config/server.xml
_backend/services/user-service/src/main/java/com/accounts/AccountService.java
_backend/services/user-service/src/main/java/com/accounts/AccountsResource.java

endpoints protected:
-Quotes
- create, update, delete 
-Accounts
- update, delete

added endpoint protection to accounts and quotes

---

frontend/src/main/frontend/package-lock.json
frontend/src/main/frontend/package.json
frontend/src/main/frontend/src/App.css
frontend/src/main/frontend/src/TopNav.css
frontend/src/main/frontend/src/components/TopNavigation.jsx

- Added tabs to top navigation
- Changed styling to match usability designs

TopNav styling updated

---

frontend/src/main/frontend/src/components/Layout.jsx
frontend/src/main/frontend/src/components/Login.jsx

Login Popup Complete

---

frontend/src/main/frontend/src/App.jsx
frontend/src/main/frontend/src/pages/SearchPage.jsx

Functional searching, I keep pushing to this branch unintentionally lol, ill finally close it

Search results

---

docker-compose.yml
frontend/src/main/frontend/package-lock.json
frontend/src/main/frontend/package.json
frontend/src/main/frontend/src/components/QuoteForm.jsx
frontend/src/main/frontend/src/components/QuoteUploadModal.jsx
frontend/src/main/frontend/src/lib/api.js
package-lock.json

Made it possible to make quotes public or private when creating or editing quotes.
Files edited: 
- api.js
- QuoteForm.jsx
- QuoteUpdateModal.jsx

Added Public/Private functionality to quotes

---

_backend/services/quote-service/src/main/java/com/quotes/QuotesRetrieveAccount.java
_backend/services/user-service/src/main/java/com/accounts/BookmarkResource.java
_backend/services/user-service/src/main/java/com/accounts/QuoteClient.java

This is my pull request to add bookmarking. It consists of two new files QuoteClient.java & BookmarkResource.java. QuoteClient is injected into BookmarkResource to hit the appropriate endpoints to search for and update a quote when bookmarking. A change is made to QuotesRetrieveAccount so that I can pass the jwt from a backend request. The cookie is parsed manually from the request in BookmarkResource and added as a header to the update quote request and verified in QuotesRetrieveAccount

Bookmarking pr 

---

.gitignore
frontend/src/main/frontend/src/App.jsx
frontend/src/main/frontend/src/lib/api.js
frontend/src/main/frontend/src/pages/AccountPage.jsx

do http://localhost:9080/account to access it

Account Homepage added

---

_backend/services/quote-service/src/main/java/com/quotes/QuoteCreateResource.java
_backend/services/quote-service/src/main/java/com/quotes/QuoteDeleteResource.java
_backend/services/quote-service/src/main/java/com/quotes/QuotesUpdateResource.java
_backend/services/user-service/src/main/java/com/accounts/AccountsResource.java

Fix to the issue opened by Matt

user update/delete quotes bug fix

---

_backend/services/user-service/src/main/java/com/auth/AuthResource.java
frontend/src/main/frontend/src/App.jsx
frontend/src/main/frontend/src/components/QuoteCard.jsx
frontend/src/main/frontend/src/pages/AccountSetup.jsx

Setup account upon new account creation

Setup account page

---

frontend/src/main/frontend/src/App.jsx
frontend/src/main/frontend/src/components/Layout.jsx
frontend/src/main/frontend/src/components/TopNavigation.jsx
frontend/src/main/frontend/src/lib/Contexts.jsx
frontend/src/main/frontend/src/lib/api.js
frontend/src/main/frontend/src/pages/AccountPage.jsx
frontend/src/main/frontend/src/pages/LoginPage.jsx
frontend/src/main/frontend/src/pages/SavedQuotes.jsx

This wasn't explicitly a task, but I noticed while reviewing #95 that we were doing some weird stuff with fetching users, so I thought I'd try my hand at fixing it:
**Before this pull request**, we were fetching the user using the `/whoami` endpoint for every function our site used, and that looked something like this:
```js
const [user, setUser] = useState(null);
useEffect(() => {
(async () => {
try {
console.log("Fetching user..."); 
const data = await fetchMe();
if (data != null) {
setUser(data);
}
} catch (err) {
console.error("Error fetching user", err);
} 
})();
}, []);
```
This works, but every time you have a component that needs to know who's logged in, you end up sending another request to the backend (which quickly escalates into way more web requests than we need)
So, for …

Cleanup: Use `Context` for getting the logged in user (or lack therof)

---

frontend/src/main/frontend/src/components/QuoteCard.jsx

Should work this time. 
Context makes things SO MUCH EASIER!

Added user context to QuoteCard

---

frontend/src/main/frontend/src/components/QuoteCard.jsx
frontend/src/main/frontend/src/components/QuoteList.jsx
frontend/src/main/frontend/src/components/QuoteViewModal.jsx

Adds a simple modal to view a quote for when you click on a quote when not logged in, or don't have access to edit the quote.
There was a very basic style on the figma sheet that I thought might change so I didn't follow it too much, but most if it should work.

Basic View Quote Modal

---

frontend/src/main/frontend/src/components/QuoteCard.jsx

Still has the My collection user context issue " set user id is not defined "

Bookmarking fix

---

frontend/src/main/frontend/src/pages/AccountPage.jsx

I fixed the bug where editing the profession or personal quote but cancelling gets you stuck

Fixed Account page bug

---

_backend/services/user-service/src/main/java/com/usedQuotes/UsedQuoteResource.java

New end point to retrieve a used quote. Will discuss alternative solutions with engine and requirements during class to make obtaining UsedQuote data easier for GUI.

Retrieve used quote

---

frontend/src/main/frontend/src/components/AlertMessage.jsx
frontend/src/main/frontend/src/components/Login.jsx
frontend/src/main/frontend/src/components/LoginOverlay.jsx
frontend/src/main/frontend/src/components/QuoteCard.jsx
frontend/src/main/frontend/src/pages/LoginPage.jsx

Instead of redirecting to login page, login will pop up, with alert, for every action other than copy

Improved guest feedback

---

frontend/src/main/frontend/src/components/QuoteCard.jsx

Added a Use/Used button to the Quote Cards. 
Currently does not talk to the backend.

Added Use button to Quote Cards

---

docker-compose.yml
frontend/src/main/frontend/src/components/QuoteForm.jsx
frontend/src/main/frontend/src/components/QuoteUploadModal.jsx
frontend/src/main/frontend/src/components/Splash.jsx
frontend/src/main/frontend/src/components/TopNavigation.jsx
frontend/src/main/frontend/src/scss/styles.scss

fixed upload and edit quotes based on usability guidelines. Also Fixed the top nav bar to be clearly visible when scrolling down.

fixed upload and edit quotes and fixed nav bar

---

_backend/services/user-service/src/main/java/com/usedQuotes/UsedQuoteResource.java

Now instead of returning the result of updating user or the full used quote the used quote end point just returns the date upon use.

Return date when using a quote

---

_backend/services/user-service/src/main/java/com/auth/AuthResource.java
frontend/src/main/frontend/package-lock.json
frontend/src/main/frontend/src/App.jsx
frontend/src/main/frontend/src/components/QuoteList.jsx
frontend/src/main/frontend/src/pages/AccountSetup.jsx
frontend/src/main/frontend/src/pages/LandingPage.jsx
frontend/src/main/frontend/src/pages/SavedQuotes.jsx

Account Page Popup Fix

---

_backend/services/quote-service/src/main/java/com/quotes/QuoteDeleteResource.java
_backend/services/user-service/src/main/java/com/usedQuotes/UsedQuoteResource.java

ObjectId is now deleted from the Users MyQuotes list upon deletion of the actual quote.

MyQuotes fix

---

_backend/services/quote-service/src/main/java/com/quotes/QuoteSearchResource.java

some searching endpoints were unnecessarily JWT protected

search endpoints protection fix

---

frontend/src/main/frontend/src/App.css
frontend/src/main/frontend/src/components/Sidebar.jsx

- Matched Usability's yellow & black bar styling. 
- Made the Sidebar collapsable.

Updated Sidebar Styling.

---

_backend/services/user-service/src/main/java/com/notifications/NotificationResource.java

makes sure the 'to' user exists for creating and getting notifications. makes sure 'quote_id' exists when creating a quote

notification endpoint checks

---

frontend/src/main/frontend/src/pages/LandingPage.jsx

Issues with the backend, but itll come soon

Login Page Start

---

.gitignore
_backend/services/quote-service/Dockerfile
_backend/services/user-service/Dockerfile
docker-compose.yml

Fix deployment docker build & switch docker database to Atlas

---

_backend/services/quote-service/src/main/java/com/quotes/QuoteSearchResource.java
frontend/src/main/frontend/src/components/FilteredSearch.jsx
frontend/src/main/frontend/src/components/Splash.jsx
frontend/src/main/frontend/src/lib/api.js
frontend/src/main/frontend/src/pages/DebugPage.jsx
frontend/src/main/frontend/src/pages/SearchPage.jsx

Filtering search functions, changed search to work for guests, Ignoring backend error for empty query for now, needs to be updated, ill send a message in discord about it

Filtered search

---

_backend/services/user-service/src/main/java/com/accounts/Account.java
_backend/services/user-service/src/main/java/com/accounts/AccountService.java
_backend/services/user-service/src/main/java/com/accounts/BookmarkResource.java
_backend/services/user-service/src/main/java/com/sharedQuotes/SharedQuote.java
_backend/services/user-service/src/main/java/com/sharedQuotes/SharedQuotesResource.java

Users can now share quotes. The Share quote end point takes a user id (receiver of the message) and a quoteId (The id of the quote being shared). These are added to a new object, SharedQuote with 3 fields. String To: User id of recipient, String From: User id or sender, and String quoteId the id of the quote being sent. This object is added to both the sender and receiver's List of SharedQuotes. In addition sharing a quote creates a matching notification with the same To,From, and QuoteId fields. There is also one addition field that is filled which is the notification type (in this case just "Share"). The id of this new object is added to the receivers Notififcations list.   In addition users can also bookmark their own quotes if they'd like to now

Share Quotes

---

_backend/services/user-service/src/main/java/com/sharedQuotes/SharedQuotesResource.java

Changed share quote endpoint to take an email for now to be easier to use. The request to the notification was broken as well becauses it protected now so I added the authHeader to the programmatic request to create notification.

SharedQuote fixes

---

frontend/src/main/frontend/src/components/QuoteList.jsx
frontend/src/main/frontend/src/components/QuoteViewModal.jsx
frontend/src/main/frontend/src/pages/AccountPage.jsx
frontend/src/main/frontend/src/pages/LandingPage.jsx

Added functioning buttons inside ViewQuoteModal for copying, sharing, bookmarking, reporting, and using quotes.
Moved logout button to account page

quote button functionality

---

frontend/src/main/frontend/src/components/NotificationDropdown.jsx

Fixed a minor issue where guests could view the account page link.

Fixed account page link appearing for Guests.

---

frontend/src/main/frontend/src/components/Sidebar.jsx
frontend/src/main/frontend/src/pages/MyCollection.jsx

I will break this up when I can, Sidebar styling to match usability

Poof (Sidebar)

---

frontend/src/main/frontend/src/components/Login.jsx
frontend/src/main/frontend/src/components/Sidebar.jsx
frontend/src/main/frontend/src/pages/MyCollection.jsx
frontend/src/main/frontend/src/pages/SearchPage.jsx

Initialize quote collections to be empty, add shared to my collection, add quote view modal to search page, fix x on LoginBox not functioning 
Other issues raised were fixed on April 11th in my last PR

QA issues 173, 176, 177, 178, 179, 180, 184

---

frontend/src/main/frontend/src/App.jsx
frontend/src/main/frontend/src/components/NotificationDropdown.jsx
frontend/src/main/frontend/src/pages/CommunityGuidelinesPage.jsx

- Create a page that contains the Community Guidelines.
- Added isArray statements to notification calls in Notification Dropdown. Page would break without them.

Community Guidelines Page

---

_backend/services/quote-service/src/main/java/com/moderation/DeleteService.java
_backend/services/quote-service/src/main/java/com/quotes/QuoteDeleteResource.java
_backend/services/user-service/src/main/java/com/notifications/NotificationResource.java
_backend/services/user-service/src/main/java/com/notifications/NotificationService.java
_backend/services/user-service/src/main/java/com/sharedQuotes/SharedQuotesResource.java
frontend/src/main/frontend/src/lib/api.js

get notification endpoint created for popup when user clicks on a notification

admin delete working and get notification endpoint

---

_backend/services/user-service/src/main/java/com/accounts/AccountService.java
_backend/services/user-service/src/main/java/com/accounts/AccountsResource.java
_backend/services/user-service/src/test/java/com/accounts/AccountsUnitTest.java

returns json containing email and username of all matches

search user by query

---

frontend/src/main/frontend/src/App.css
frontend/src/main/frontend/src/buttons/QuoteActions.jsx
frontend/src/main/frontend/src/components/QuoteList.jsx
frontend/src/main/frontend/src/components/QuoteViewModal.jsx
frontend/src/main/frontend/src/components/ReportModal.jsx

- created report modal
- updated QuoteActions for report button functionality
- added rounded button styling
- no backend integration because no service that matches the expected behavior exists

report modal dialog UI only (no service integration)

---

frontend/src/main/frontend/src/buttons/QuoteActions.jsx
frontend/src/main/frontend/src/components/ReportModal.jsx
frontend/src/main/frontend/src/lib/api.js

- Connected the reporting UI to backend functionality 
- The user can now successfully report a quote

report modal now connected to backend

---

frontend/src/main/frontend/src/components/Notification.jsx
frontend/src/main/frontend/src/components/NotificationDropdown.jsx
frontend/src/main/frontend/src/lib/api.js

Styling complete and functionality should be complete. My development environment is extremely buggy and inconsistent, and I do not have access to the database to properly test notifications. HOWEVER - The console errors originally being thrown from the fetchNotifications function have been resolved, and the styling is complete.

Notification System

---

_backend/services/quote-service/src/main/java/com/moderation/ProfanityClass.java
_backend/services/quote-service/src/main/java/com/quotes/QuoteCreateResource.java
_backend/services/quote-service/src/main/java/com/quotes/QuotesUpdateResource.java
_backend/services/user-service/src/main/java/com/accounts/AccountService.java
_backend/services/user-service/src/main/java/com/moderation/ProfanityClass.java

added profanity filters where needed

Profanity filter

---

_backend/services/quote-service/src/main/java/com/moderation/ReportResource.java
frontend/src/main/frontend/src/App.jsx
frontend/src/main/frontend/src/components/TopNavigation.jsx
frontend/src/main/frontend/src/lib/api.js
frontend/src/main/frontend/src/pages/AdminPanel.jsx

Can we please update error message when making new endpoints 🙏

Start of Admin panel

---

frontend/src/main/frontend/src/components/ShareQuotePopup.jsx

Not functional with backend yet

Share quote search

---

_backend/services/user-service/src/main/java/com/auth/AuthResource.java

To use endpoint:
http://localhost:9081/users/auth/PlaywrightLogin/username/password

implemented an endpoint to bypass google oauth

---

frontend/src/main/frontend/src/components/QuoteViewModal.jsx
frontend/src/main/frontend/src/lib/api.js

Starting this for Joseph - user who uploaded quote

Display User who uploaded quote

---

frontend/src/main/frontend/src/components/FilteredSearch.jsx
frontend/src/main/frontend/src/components/Splash.jsx
frontend/src/main/frontend/src/lib/api.js
frontend/src/main/frontend/src/pages/SearchPage.jsx

- Added filtered search to landing page
- When filter is invoked in this context, it stores the user's filter settings and passes them to the search page using state
- The search page retrieves filters from state and passes them to the filteredSearch API
- filteredSearch API POST was not working.  Everything is going through GET (guest avenue).

filtered search now accessible from landing splash page (global search)

---

frontend/src/main/frontend/src/App.jsx
frontend/src/main/frontend/src/components/DeleteQuoteModal.jsx
frontend/src/main/frontend/src/components/QuoteCardAdmin.jsx
frontend/src/main/frontend/src/components/ReportModal.jsx
frontend/src/main/frontend/src/components/ReportedQuoteCard.jsx
frontend/src/main/frontend/src/components/ShareQuotePopup.jsx
frontend/src/main/frontend/src/pages/AdminPanel.jsx
frontend/src/main/frontend/src/pages/QuotePage.jsx

worked on DeleteQuoteModal.jsx and 
ReportedQuoteCard.jsx

admin page

---

frontend/src/main/frontend/src/pages/SearchPage.jsx

- Removed Funnel Button
- Replaced Funnel button with "Filter Search" button.
- added a <hr/>.

Updated search page to follow Figma Design

---

frontend/src/main/frontend/src/components/LoginOverlay.jsx
frontend/src/main/frontend/src/pages/LandingPage.jsx

found out about useRef and tabIndex="-1". Should fix the popup alert problem.

Possible fix for issue #108

---

frontend/src/main/frontend/src/components/Sidebar.jsx
frontend/src/main/frontend/src/pages/MyCollection.jsx

1. prioritize quotes with all selected tags, sorted by relevance
2. fixed the uploaded quotes section, was just displaying all public quotes under uploaded before
3. usememo to filter out uploaded quotes before render

Issue #180 - Sorting filtered tag results + fix uploaded quote section, switch to usememo

---

frontend/src/main/frontend/src/buttons/QuoteActions.jsx
frontend/src/main/frontend/src/components/ReportedQuoteCard.jsx
frontend/src/main/frontend/src/components/SidebarAdmin.jsx
frontend/src/main/frontend/src/pages/AdminPanel.jsx

Admin Page Filtering works now, used delimiter instead. Console logs removed.

Admin Page Filtering
